PPPK_MVC/Zadatak/Models/PutniNalog.cs
namespace Zadatak.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Serialization;

    public class PutniNalog
    { 

        [Key]
        [XmlElement("idPutniNalog")]
        public int? IDPutniNalog { get; set; }

        [Required]
        [XmlElement("vozacId")]
        public int? VozacID { get; set; }
        [XmlElement("voziloId")]
        public int? VoziloID { get; set; }


        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [XmlElement("datumOdlaska")]
        public DateTime? DatumOdlaska { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [XmlElement("datumDolaska")]
        public DateTime? DatumDolaska { get; set; }

        [XmlElement("brojSati")]
        public int? BrojSati { get; set; }
        [XmlElement("brojDnevnica")]
        public int? BrojDnevnica { get; set; }
        [XmlElement("iznosDnevnice")]
        public int? IznosDnevnice { get; set; }

        [StringLength(100)]
        [XmlElement("opis")]
        public string Opis { get; set; }

        [XmlIgnore]
        public virtual Vozac Vozac { get; set; }

        [XmlIgnore]
        public string PrikazNaloga
        {
            get
            {
                return "ID: " + IDPutniNalog + ", " + Vozac.FirstName + " " + Vozac.LastName + ", " + DatumOdlaska;
            }
        }
    }
}

PPPK_MVC/Zadatak/Models/PutniNalogViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Zadatak.Models
{
    public class PutniNalogViewModel
    {

        public int IDPutniNalog { get; set; }

        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public int? VozacID { get; set; }

        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public int? VoziloID { get; set; }

        public int? GradID { get; set; }

        public int? DrzavaID { get; set; }

        public IEnumerable<Vozac> ListaVozaca { get; set; }
        public IEnumerable<Vozilo> ListaVozila { get; set; }
        public IEnumerable<Grad> ListaGradova { get; set; }

        public IEnumerable<Drzava> ListaDrzava { get; set; }


        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Datum odlaska")]
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public DateTime? DatumOdlaska { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Datum dolaska")]
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public DateTime? DatumDolaska { get; set; }


        [Display(Name = "Broj sati")]
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public int? BrojSati { get; set; }

        [Display(Name = "Broj dnevnica")]
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public int? BrojDnevnica { get; set; }

        [Display(Name = "Iznos dnevnice")]
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public int? IznosDnevnice { get; set; }

        [StringLength(100)]
        [Display(Name = "Opis")]
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        public string Opis { get; set; }


        public virtual Vozac Vozac { get; set; }


        public virtual Vozilo Vozilo { get; set; }

        public virtual StanjePutnogNaloga Stanje { get; set; }

        public PutniNalogViewModel()
        {

        }

        public void NamjestiStanje()
        {
            if (DatumOdlaska != null && DatumDolaska != null)
            {
                if (DateTime.Now > DatumOdlaska && DateTime.Now < DatumDolaska)
                {
                    Stanje = new StanjePutnogNaloga(StanjePutnogNaloga.Tip.Otvoreni, "green");
                }
                else if (DateTime.Now < DatumOdlaska && DateTime.Now < DatumDolaska)
                {
                    Stanje = new StanjePutnogNaloga(StanjePutnogNaloga.Tip.Buduci, "powderblue");
                }
                else
                {
                    Stanje = new StanjePutnogNaloga(StanjePutnogNaloga.Tip.Zatvoreni, "red");
                }

            }
        }

        public string Ukupno
        {
            get
            {
                return IznosZaPlatiti() + " kn";
            }
        }

        public int IznosZaPlatiti()
        {
            int a = BrojSati.HasValue ? Convert.ToInt32(BrojSati) : 0;
            int b = BrojDnevnica.HasValue ? Convert.ToInt32(BrojDnevnica) : 0;
            int c = IznosDnevnice.HasValue ? Convert.ToInt32(IznosDnevnice) : 0;
            return (b * c) * a;
        }
    }
}

PPPK_MVC/Zadatak/Controllers/PutniNalogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Zadatak.Models;
using Zadatak.Models.Database;

namespace Zadatak.Controllers
{
    public class PutniNalogController : Controller
    {
        PutniNalogRepository putniNalogRepository = new PutniNalogRepository();
        IRepository<Vozac> vozacRepository = new VozacRepository();
        IRepository<Vozilo> voziloRepository = new VoziloRepository();
        IRepository<Drzava> drzavaRepository = new DrzavaRepository();
        GradRepository gradRepository = new GradRepository();
        // GET: PutniNalog
        public ActionResult Index()
        {
            List<PutniNalog> nalozi = putniNalogRepository.List().ToList();
            List<PutniNalogViewModel> model = new List<PutniNalogViewModel>();
            foreach (PutniNalog item in nalozi)
            {
                PutniNalogViewModel putniNalogVM = new PutniNalogViewModel
                {
                    Vozac = vozacRepository.GetById(item.VozacID),
                    Vozilo = voziloRepository.GetById(item.VoziloID),
                    BrojDnevnica = item.BrojDnevnica,
                    BrojSati = item.BrojSati,
                    IDPutniNalog = item.IDPutniNalog.Value,
                    IznosDnevnice = item.IznosDnevnice,
                    Opis = item.Opis,
                    DatumDolaska = item.DatumDolaska,
                    DatumOdlaska = item.DatumOdlaska
                };
                putniNalogVM.NamjestiStanje();
                model.Add(putniNalogVM);
            }
            //var putniNalozi = db.PutniNalozi.Include(p => p.Vozac);
            return View(model);
        }

        // GET: PutniNalog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PutniNalog putniNalog = null; //OVDJE IDE FIND
            if (putniNalog == null)
            {
                return HttpNotFound();
            }
            return View(putniNalog);
        }

        public ActionResult Create()
        {
            var model = new PutniNalogViewModel
            {
                ListaVozaca = vozacRepository.List(),
                ListaVozila = voziloRepository.List(),
                ListaDrzava = drzavaRepository.List(),
                ListaGradova = gradRepository.List()
            };
            return View(model);
        }

        public JsonResult GetGradovi(int drzava)
        {
            return Json(gradRepository.GetByDrzava(drzava).ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PutniNalogViewModel putniNalog)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                PutniNalog nalog = new PutniNalog
                {
                    VozacID = putniNalog.VozacID,
                    VoziloID = putniNalog.VoziloID,
                    BrojSati = putniNalog.BrojSati,
                    BrojDnevnica = putniNalog.BrojDnevnica,
                    DatumDolaska = putniNalog.DatumDolaska,
                    DatumOdlaska = putniNalog.DatumOdlaska,
                    IznosDnevnice = putniNalog.IznosDnevnice,
                    Opis = putniNalog.Opis
                };
                putniNalogRepository.Add(nalog);
                //db.PutniNalozi.Add(putniNalog);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            putniNalog.ListaVozaca = vozacRepository.List();
            putniNalog.ListaVozila = voziloRepository.List();
            putniNalog.ListaGradova = gradRepository.List();
            putniNalog.ListaDrzava = drzavaRepository.List();
            return View(putniNalog);
        }

        // GET: PutniNalog/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PutniNalog putniNalog = putniNalogRepository.GetById(id);
            if (putniNalog == null)
            {
                return HttpNotFound();
            }
            var model = new PutniNalogViewModel
            {
                ListaVozaca = vozacRepository.List(),
                ListaVozila = voziloRepository.List(),
                BrojDnevnica = putniNalog.BrojDnevnica,
                BrojSati = putniNalog.BrojSati,
                DatumDolaska = putniNalog.DatumDolaska,
                DatumOdlaska = putniNalog.DatumOdlaska,
                Opis = putniNalog.Opis,
                IznosDnevnice = putniNalog.IznosDnevnice,
                VozacID = putniNalog.VozacID,
                VoziloID = putniNalog.VoziloID,
                Vozac = putniNalog.Vozac,
                IDPutniNalog = putniNalog.IDPutniNalog.Value

            };
            //ViewBag.VozacID = new SelectList(Models.SqlHandler.GetVozaci(), "IDVozac", "FirstName", putniNalog.VozacID);
           // ViewBag.VoziloID = new SelectList(Models.SqlHandler.GetVozila(), "IDVozilo", "FirstName", putniNalog.VozacID);
            return View(model);
        }

        // POST: PutniNalog/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PutniNalogViewModel putniNalog)
        {
            if (ModelState.IsValid)
            {
                PutniNalog nalog = new PutniNalog
                {
                    VozacID = putniNalog.VozacID,
                    IDPutniNalog = putniNalog.IDPutniNalog,
                    VoziloID = putniNalog.VoziloID,
                    BrojSati = putniNalog.BrojSati,
                    BrojDnevnica = putniNalog.BrojDnevnica,
                    DatumDolaska = putniNalog.DatumDolaska,
                    DatumOdlaska = putniNalog.DatumOdlaska,
                    IznosDnevnice = putniNalog.IznosDnevnice,
                    Opis = putniNalog.Opis
                };
                putniNalogRepository.Update(nalog);
                return RedirectToAction("Index");
            }
            return View(putniNalog);
        }

        // GET: PutniNalog/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PutniNalog putniNalog = putniNalogRepository.GetById(id);
            if (putniNalog == null)
            {
                return HttpNotFound();
            }
            PutniNalogViewModel model = new PutniNalogViewModel
            {
                Vozac = vozacRepository.GetById(putniNalog.VozacID),
                Vozilo = voziloRepository.GetById(putniNalog.VoziloID),
                BrojDnevnica = putniNalog.BrojDnevnica,
                BrojSati = putniNalog.BrojSati,
                IDPutniNalog = putniNalog.IDPutniNalog.Value,
                IznosDnevnice = putniNalog.IznosDnevnice,
                Opis = putniNalog.Opis,
                DatumDolaska = putniNalog.DatumDolaska,
                DatumOdlaska = putniNalog.DatumOdlaska
            };
            return View(model);
        }

        // POST: PutniNalog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            putniNalogRepository.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

PPPK_MVC/Zadatak/Views/PutniNalog/Create.cshtml
@model Zadatak.Models.PutniNalogViewModel

@{
    ViewBag.Title = "Novi putni nalog";
}

<h2>Dodaj</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PutniNalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VozacID, "Vozac", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VozacID", new SelectList(Model.ListaVozaca, "IDVozac", "PunoIme"), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VoziloID, "Vozilo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VoziloID", new SelectList(Model.ListaVozila, "IDVozilo", "PunoIme"), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumOdlaska, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumOdlaska, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumOdlaska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumDolaska, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumDolaska, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.DatumDolaska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojSati, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojSati, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojSati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojDnevnica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojDnevnica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojDnevnica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IznosDnevnice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IznosDnevnice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IznosDnevnice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        $(function () {
            $('#DatumOdlaska, #DatumDolaska').datepicker({
                dateFormat: 'dd/mm/yy'
            });
            $('#DrzavaID').on('change', function() {
                var gradDropdown = $('#GradID');

                gradDropdown.empty();

                gradDropdown.removeAttr('disabled');

                var drzava = $(this).val();
                console.log(drzava);
                    $.getJSON('@Url.Action("GetGradovi","PutniNalog",null)', {
                        drzava: drzava
                    })
                        .done(function (data) {
                        $.each(data, function (i, grad) {
                            var option = $('<option />', {
                                value: grad['IDGrad'],
                                text: grad['Naziv']})
                            console.log(grad);
                            gradDropdown.append(option);
                        });
                    })
                    .fail(function (jqxhr, textStatus, error) {
                        var err = textStatus + ", " + error;
                        console.log("Request Failed: " + err);
                    });
            });
        })
    </script>
}

PPPK_MVC/Zadatak/Views/PutniNalog/Delete.cshtml
@model Zadatak.Models.PutniNalogViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PutniNalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vozac.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vozac.PunoIme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vozilo.PunoIme)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.Vozilo.PunoIme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumOdlaska)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumOdlaska)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumDolaska)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumDolaska)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojSati)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojSati)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojDnevnica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojDnevnica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IznosDnevnice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IznosDnevnice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-default" /> |
            @Html.ActionLink("Povratak", "Index")
        </div>
    }
</div>

PPPK_MVC/Zadatak/Views/PutniNalog/Details.cshtml
@model Zadatak.Models.PutniNalog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PutniNalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vozac.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vozac.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumOdlaska)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumOdlaska)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumDolaska)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumDolaska)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojSati)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojSati)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojDnevnica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojDnevnica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IznosDnevnice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IznosDnevnice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDPutniNalog }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PPPK_MVC/Zadatak/Views/PutniNalog/Edit.cshtml
@model Zadatak.Models.PutniNalogViewModel

@{
    ViewBag.Title = "Uređivanje putnog naloga";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Putni Nalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDPutniNalog)
        <div class="form-group">
            @Html.LabelFor(model => model.VozacID, "Vozac", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VozacID", new SelectList(Model.ListaVozaca, "IDVozac", "PunoIme"), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.VoziloID, "Vozilo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VoziloID", new SelectList(Model.ListaVozila, "IDVozilo", "PunoIme"), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumOdlaska, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumOdlaska, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumOdlaska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumDolaska, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumDolaska, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.DatumDolaska, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojSati, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojSati, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojSati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojDnevnica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojDnevnica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojDnevnica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IznosDnevnice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IznosDnevnice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IznosDnevnice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        $(function () {
            $('#DatumOdlaska, #DatumDolaska').datepicker({
                dateFormat: 'dd/mm/yy'
            });
        })
    </script>
}

PPPK_MVC/Zadatak/Views/PutniNalog/Index.cshtml
@model IEnumerable<Zadatak.Models.PutniNalogViewModel>

@{
    ViewBag.Title = "Pregled putnih naloga";
}

<h2>Putni nalozi</h2>
<div class="row" style="margin-bottom:10px;">
    <div class="col-lg-3 col-md-3 col-sm-3">
        <select class="form-control" id="ddlFilterType">
            <option value="@Html.DisplayNameFor(model => model.Vozac.FirstName)">Ime</option>
            <option value="@Html.DisplayNameFor(model => model.Vozilo.PunoIme)">Vozilo</option>
            <option value="@Html.DisplayNameFor(model => model.DatumOdlaska)">Datum odlaska</option>
            <option value="@Html.DisplayNameFor(model => model.DatumDolaska)">Datum dolaska</option>
            <option value="@Html.DisplayNameFor(model => model.BrojSati)">Broj sati</option>
            <option value="@Html.DisplayNameFor(model => model.BrojDnevnica)">Broj dnevnica</option>
            <option value="@Html.DisplayNameFor(model => model.IznosDnevnice)">Iznos dnevnice</option>
        </select>
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3">
        <input type="text" class="form-control" id="tbFilterText" />
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3">
        <input type="button" id="btnFilter" value="Filter" class="btn btn-primary" />
        <input type="button" id="btnReset" value="Reset" class="btn btn-dark" />

    </div>
    <div class="col-lg-3 col-md-3 col-sm-3">
    </div>
</div>

@Html.Partial("~/Views/AJAX/_PutniNalogTablica.cshtml", Model)



@Html.ActionLink("Relacije", "Index", "Relacija", null, null) |
@Html.Partial("~/Views/Shared/_Navigation.cshtml")

@section Scripts {
    <script type="text/javascript">
        $(function () {

            $('#btnFilter').click(function () {
                var searchQuery = $('#tbFilterText').val();
                var filterProp = $('#ddlFilterType').find(":selected").text();
                $.ajax({
                    url: "http://localhost:56803/AJAX/Filter",
                    method: "GET",
                    data: { 'searchQuery': searchQuery, 'filterProp': filterProp },
                    success: (data) => {
                        $('.table').html(data);
                    }
                });
                console.log(searchQuery);
            });

            $('#btnReset').click(function () {
                $.ajax({
                    url: "http://localhost:56803/AJAX/Filter",
                    method: "GET",
                    success: (data) => {
                        $('.table').html(data);
                        $('#tbFilterText').val('');
                    }
                }); 
            })
        });
    </script>

}